### ISSUE TITLE
Tüm controller'lara summary'ler eklendi. Dokümantasyon oluşturuldu.

### ISSUE THREAD

**Issue by ozgegoseli** [EKON-YAZILIM/ServicesDAO#8]

**Comment by mrkara** [comment]
Merhaba @ozgegoseli ! :)

Issue'larda genelde yapılacak işi tanımlıyoruz. "Tüm controller'lara summary eklenmeli" ya da "Bazı controller'larda summary eksik" gibi.

Daha sonra, bu issue'yu çözecek commitleri içeren bir PR (Pull Request) oluşturup, başlık kısmında "Resolves #ISSUENUMBER" gibi bir şey yazarak belirtiyoruz. (Örneğin, bu issuenun numarası 8 olduğu için: "Resolves #8")

İlgili PR merge edildikten sonra da gelip issue'yu kapatıyoruz.

Değişiklikleri hep PR ile depoya işlemek ve her seferinde GitHub'daki otomatik testlerden geçtiğini görmek her zaman daha iyidir.

Saygılar, sevgiler.
